version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    networks:
      - myapp
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data/mysql/conf:/etc/mysql/conf.d
      - ./data/mysql/data:/var/lib/mysql
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    networks:
      - myapp
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: always
    networks:
      - myapp
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    user: root
    networks:
      - myapp
    ports:
      - 8080:8080
    volumes:
      - ./data/jenkins_home:/var/jenkins_home
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  myapp:
    driver: bridge
    