version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    user: root
    ports:
      - 8080:8080
    volumes:
      - ./data/jenkins_home:/var/jenkins_home
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock  
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data/mysql/conf:/etc/mysql/conf.d
      - ./data/mysql/data:/var/lib/mysql
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
  redis-stack-server:
    image: redis/redis-stack-server:6.2.6-v9
    container_name: redis-stack-server
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./mongo/data:/data/db
  doocs:
    image: node:20-alpine
    container_name: doocs
    restart: always
    tty: true
    ports:
      - 9000:9000
    command: /bin/sh -c "npm i -g @doocs/md-cli && md-cli port=9000"
  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - ./loki:/var/tmp
    command: -config.file=/var/tmp/local-config.yaml
  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail
    restart: always
    volumes:
      - /Users/tao.huang/log:/var/log
      - ./promtail:/var/tmp
    command: -config.file=/var/tmp/config.yml
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3001:3000"
  rmqnamesrv:
    image: apache/rocketmq:5.3.0
    container_name: rmqnamesrv
    restart: always
    ports:
      - "9876:9876"
    command: sh mqnamesrv
  rmqbroker:
    image: apache/rocketmq:5.3.0
    container_name: rmqbroker
    restart: always
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
    depends_on:
      - rmqnamesrv
    command: sh mqbroker
  rmqproxy:
    image: apache/rocketmq:5.3.0
    container_name: rmqproxy
    restart: always
    ports:
      - "10915:8080"
      - "10916:8081"
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
    depends_on:
      - rmqbroker
      - rmqnamesrv
    command: sh mqproxy
  rmqdashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rmqdashboard
    restart: always
    ports:
      - "10920:8080"
    environment:
      - "JAVA_OPTS=-Drocketmq.namesrv.addr=rmqnamesrv:9876"
  


    
